name: flutter_app_security_detected
description: flutter_app_security_detected lib allow your app to detected security device both(dev and jailbreak).
version: 1.0.0
homepage: https://github.com/kdrtech/flutter_app_security_detected
environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  flutter:
    sdk: flutter
  flutter_jailbreak_detection: ^1.10.0
  restart_app: ^1.2.1
dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
